### ISSUE TITLE
No output files using "example_world3_standard.py"

### ISSUE THREAD

**Issue by 012abcd** [cvanwynsberghe/pyworld3#1]
Hello,

I try your script. I can't find the "fig_world3_standard_x.pdf" files anywhere after using "example_world3_standard.py".

I'm not confortable with Python, so may be I don't use the script properly.

Regards.

**Comment by cvanwynsberghe** [comment]
Did you install pyworld3 via pip / python setup install, or you just downloaded on Github?

As such, if you run in the console
```bash
python example_world3_standard.py
```
the figures should be saved in the current directory, i.e. where the file example_world3_standard.py is since they are saved with the lines
```python
plt.savefig("fig_world3_standard_x.pdf")
```

**Comment by 012abcd** [comment]
Hello,

I have the "\AppData\Local\pip\" and the "\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyworld3\" folders.

I moved to the "example_world3_standard.py" folder,
then CMD "python example_world3_standard.py",
and i get the three following pdfs:

[fig_world3_standard_c.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972140/fig_world3_standard_c.pdf)
[fig_world3_standard_a.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972141/fig_world3_standard_a.pdf)
[fig_world3_standard_b.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972142/fig_world3_standard_b.pdf)

Is the output correct?

But i can't findout how to do: "Run the provided example to simulate the standard run, known as the Business as usual scenario:
```
import pyworld3
pyworld3.hello_world3()
```
"

Both with DOS prompt and Python prompt, i have no output.


I read "Limits to Growth. The 30-Year Update" 2004 and I wished to run the simulation by myself.

You give "The Limits to Growth" 1972 as reference. So guess the code is compliant with the Meadow's World3? And not World3-2004?

I'm not confident in Dynamic systems and i'm looking for information about 'Numerical integration method: "euler" or "odeint".' I can't findout what this means.

Regards

**Comment by cvanwynsberghe** [comment]
> I have the "\AppData\Local\pip" and the "\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyworld3" folders.
> 
> I moved to the "example_world3_standard.py" folder,
> then CMD "python example_world3_standard.py",
> and i get the three following pdfs:
> 
> [fig_world3_standard_c.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972140/fig_world3_standard_c.pdf)
> [fig_world3_standard_a.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972141/fig_world3_standard_a.pdf)
> [fig_world3_standard_b.pdf](https://github.com/cvanwynsberghe/pyworld3/files/6972142/fig_world3_standard_b.pdf)
> 
> Is the output correct?

With the last version currently on pypi, it looks okay. The graph shapes seems good, just some unexcpected cosmetics (no grid, time reaches 2300 rather than 2100). I will release on pypi the updated version soon.

> But i can't findout how to do: "Run the provided example to simulate the standard run, known as the Business as usual scenario:
> ```
> import pyworld3
> pyworld3.hello_world3()
> ```
> Both with DOS prompt and Python prompt, i have no output.

Thank you for this remark. Meanwhile, try
``` python
import pyworld3
import matplotlib.pyplot as plt
pyworld3.hello_world3()
plt.show()
```
And the figure will pop up. I will fix this soon.

> I read "Limits to Growth. The 30-Year Update" 2004 and I wished to run the simulation by myself.
> You give "The Limits to Growth" 1972 as reference. So guess the code is compliant with the Meadow's World3? And not World3-2004?

Actually the same model is used in the 4 versions, only a few variables differ.

> I'm not confident in Dynamic systems and i'm looking for information about 'Numerical integration method: "euler" or "odeint".' I can't findout what this means.

Euler method is the most simple way to solve a differential equation when no analytic solution is known. It is also the less accurate one and have stability issues if the time step is too small. The original code from Meadows uses Euler, so I recommend to keep this option.

**Comment by cvanwynsberghe** [comment]
Pyworld3 is updated both on github & pip. @012abcd  could you could check on your side that the behavior is fixed with hello_world3 (figure output is visible)?

**Comment by 012abcd** [comment]
Thanks for your answers.

After update, I tried:
```
import pyworld3
pyworld3.hello_world3()
```
No output.

Then i used:
```
import pyworld3
import matplotlib.pyplot as plt
pyworld3.hello_world3()
plt.show()
```
and here is the output:
![image](https://user-images.githubusercontent.com/26328868/129893291-3b2053ff-e75e-4267-9e2f-41c98ac91710.png)

In the annexes of "Limits to Growth. The 30-Year Update" 2004, authors explained quickly how the code was updated.

"If you need to have it both ways, designing with Vensim for the ease of use, followed by an automated port to Python with PySD to keep efficiency, seems to be the most straightforward solution on paper." looks a great advise! https://towardsdatascience.com/exploring-the-limits-to-growth-with-python-674133874eed

I studied economics, and i have to admit i'm not confortable with differential equation...

May be the reading of "Thinking in Systems", Donnella Meadows, 2009 would help me.

I read this in some comnents: "Almost all engineering analyses and models especially for dynamic system are to solve “differential equations” such as the famous Newton’s law (sum of F = M*a = M*d(velocity)/dt, where velocity = d(displacement)/dt). Some examples are structural dynamics (such as bending shape of a skyscraper, bridge, and car, etc.). Computer-Aided-Engineering (CAE) is entirely based on differential equations (called finite element analysis (FEA)). Rounding error is a serious issue in computer analysis and due attention should be paid. However, rounding error is nothing to do with the World Model."

**Comment by 012abcd** [comment]
In fact, for the first run i have to do:
```
import pyworld3
import matplotlib.pyplot as plt
pyworld3.hello_world3()
plt.show()
```
then after:
`pyworld3.hello_world3()`
looks enough.

![image](https://user-images.githubusercontent.com/26328868/129899580-89525243-681e-4a4d-9506-77c3492f7908.png)

**Comment by 012abcd** [comment]
Using `python example_world3_standard.py`, looks something is missing:
```
Traceback (most recent call last):
  File ".\Mon environnement\Livres\Croissance - Limites\Scripts\pyworld3-main\example_world3_standard.py", line 18, in <module>
    plot_world_variables(world3.time,
  File ".\Mon environnement\Livres\Croissance - Limites\Scripts\pyworld3-main\pyworld3\utils.py", line 116, in plot_world_variables
    im = imread(img_background)
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\image.py", line 1501, in imread
    with img_open(fname) as image:
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\ImageFile.py", line 109, in __init__
    self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './img/fig7-7.png'
```

**Comment by 012abcd** [comment]
"pyworld3" is in two places:
.\AppData\Local\Programs\Python\Python39\Lib\site-packages\pyworld3
.\Mon environnement\Livres\Croissance - Limites\Scripts\pyworld3-main\pyworld3
with only one "\img" with "logo.png", "result_standard_run.png"
.\Mon environnement\Livres\Croissance - Limites\Scripts\pyworld3-main\img

**Comment by cvanwynsberghe** [comment]
@012abcd 
The png images were missing in the package. It is now fixed.
