### ISSUE TITLE
Missing requirement for cbr in Population

### ISSUE THREAD

**Issue by iancostalves** [cvanwynsberghe/pyworld3#5]
```
    @requires(["cbr"], ["pop"])
    def _update_cbr(self, k, jk):
        """
        From step k requires: POP
        """
        self.cbr[k] = 1000 * self.b[jk] / self.pop[k]
```

I believe the function _update_cbr in the Population class is missing the requirement for the birth rate

**Comment by cvanwynsberghe** [comment]
The requires decorator is intended to tackle dependencies at index k and kl. Other ones (j,  jk) are not needed because they are computed already.
